### ISSUE TITLE
Hyphenated tags are not handled correctly.

### ISSUE THREAD

**Issue by koichirok** [NaturalIntelligence/cytorus#1]
Cytorus 0.2.9 does not handle tags containing hyphens correctly.

I think this is because bexp treats hyphens as operators. However, the use of hyphens in tags is expected in Cucumebr, so I hope Cytorus will support tags with hyphens.

For example, for the following feature file, I would expect cytorus to run first scenario when `--tags @foo-bar` is specified.

```gherkin
Feature: test hyphenated tag expressions

@foo-bar
Scenario: should run on `@all` and `@foo-bar` expressions
    Given I start here

@only
Scenario: should run when tag expression is not given
    Given I start here
```

However, the result is that the second scenario is executed, as shown below:

```
$ npx cytorus run --tags "@foo-bar" --spec cypress/integration/features/hyphenated-tags.feature
(snip)
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  cytorus-cache/group0.cytorus                                                    (1 of 1)





  Feature: test hyphenated tag expressions

    - Scenario: should run on `@all` and `@foo-bar` expressions

    ✓ Scenario: should run when tag expression is not given (17ms)

    - Updating test results




  1 passing (246ms)

  2 pending

(snip)
```

**Comment by amitguptagwl** [comment]
Have you tried without `@only`? Because `@only` and `@skip` are special tags. Please check [--only vs @only](https://github.com/NaturalIntelligence/cytorus/blob/master/docs/5.RunStrategy.md#--only)

**Comment by amitguptagwl** [comment]
can you please try with v2.0.10. I've recently done the changes.

**Comment by koichirok** [comment]
Thank you for the update.

However, the scenario selected by `--tags "@foo-bar"` is still the first one (which tagged with `@foo`).

I think same change as 67a47ce need to be made here: https://github.com/NaturalIntelligence/cytorus/blob/67a47ce86f70d45629cca5e657246c16180eedec/src/filters/TagExpressionFilter.js#L10

**Comment by amitguptagwl** [comment]
Thanks, yes I might have missed that.

**Comment by amitguptagwl** [comment]
done that to v0.2.11

**Comment by koichirok** [comment]
Now it works fine as expected. Thanks!
